---
title: "Assignment 8"
author:
  name: Natalia
  date: 12.17.2025
format: html
---

# Assignment 8

## American voter sympathies in the Israeli–Palestinian conflict.

### Creating the first table with data from data.csv

```{r}
#adding the needed libraries
library(readr)
library(ggplot2)
library(dplyr)
library(tidyr)

#inserting the contents of data.scv into a table
data_table <- read.table(
  text = "
  Demographics;Israel;Palestine;Both;Neither
  Registered Voters;0,291;0,214;0,197;0,298
  Republicans;0,471;0,126;0,149;0,254
  Democrats;0,171;0,319;0,213;0,297
  Independents;0,201;0,201;0,238;0,36
  Republicans  18-29;0,279;0,334;0,135;0,252
  America First  25-29;0,245;0,408;0,041;0,306",
  sep = ";",
  dec = ",",
  #the first verse contains the names of the colums
  header = TRUE,
  #string must be a char type
  stringsAsFactors = FALSE)

#chance to check if the table is correct
head(data_table)
```

### Conversion of the table to long format

```{r}
#conversion to long version (on which a plot can be based)
data_long <- data_table %>%
  pivot_longer(
    #all column without "Demographics"
    cols = -Demographics,
    #creating the "Position" category
    names_to = "Position",
    values_to = "Percent"
  ) %>%
  #calculating the data so it can be shown as percents
  mutate(Percent = Percent * 100)

head(data_long)
```

### Creation of the ggplot

I strived to recreate a clustered column chart from my Assignment-6. 

It is the least illegible version of it. 

```{r}
#added to control the order of Positions
data_long$Position <- factor(data_long$Position, 
                             levels = c("Israel", "Palestine", "Both", "Neither"))

#creating a ggplot (differentiating color of the column by "Position")
ggplot(data_long, aes(x = Demographics, y = Percent, fill = Position)) +
  #creating a clustered column chart
  geom_col(position = position_dodge(width = 0.8), width = 0.7) +
  #adding cosmetics
  #additional texts over the columns
  geom_text(aes(label = paste0(Percent, "%")), 
            position = position_dodge(width = 0.8), 
            vjust = -0.5,
            size = 3) +
  #changing the colours of the columns according to the "Position"
  scale_fill_manual(values = c("Israel" = "#1874CD",
                               "Palestine" = "#CD2626",
                               "Both" = "#9F79EE",
                               "Neither" = "#CDC9C9" )) +
  #adding the title
  labs(title = "American voter sympathies in the Israeli–Palestinian conflict.",
       x = "",
       y = "") +
  #addition for easier visuals
  theme_minimal() +
  #adjusting the column group descriptions
  theme(axis.text.x = element_text(angle = -45, vjust = -1))
```

